name: Deploy to Dokku

on:
  push:
    branches: [ main ] # O deploy acontece quando você envia para a branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para o deploy do Dokku via Git

      - name: Push to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@178.156.220.69:22/f1-bortobet'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}